export const JetonRelay = {
    "abi":[
        {
            "inputs":[
                {
                    "internalType":"contract INativeTokenWrapper",
                    "name":"_nativeTokenWrapper",
                    "type":"address"
                },
                {
                    "internalType":"contract IRelayTxRecord",
                    "name":"_relayTxRecord",
                    "type":"address"
                },
                {
                    "internalType":"contract IUniswapRouterV2",
                    "name":"_uniswapV2Router",
                    "type":"address"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"constructor"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"relayer",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"initiator",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"tokenQuoteAmount",
                    "type":"uint256"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"tokenPayAmount",
                    "type":"uint256"
                }
            ],
            "name":"RelayTx",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                },
                {
                    "indexed":true,
                    "internalType":"bytes32",
                    "name":"previousAdminRole",
                    "type":"bytes32"
                },
                {
                    "indexed":true,
                    "internalType":"bytes32",
                    "name":"newAdminRole",
                    "type":"bytes32"
                }
            ],
            "name":"RoleAdminChanged",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"sender",
                    "type":"address"
                }
            ],
            "name":"RoleGranted",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"sender",
                    "type":"address"
                }
            ],
            "name":"RoleRevoked",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":false,
                    "internalType":"address",
                    "name":"oldAddr",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"address",
                    "name":"newAddr",
                    "type":"address"
                }
            ],
            "name":"UpdateJetonRouter",
            "type":"event"
        },
        {
            "inputs":[

            ],
            "name":"DEFAULT_ADMIN_ROLE",
            "outputs":[
                {
                    "internalType":"bytes32",
                    "name":"",
                    "type":"bytes32"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"getJetonRouter",
            "outputs":[
                {
                    "internalType":"address",
                    "name":"",
                    "type":"address"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"addr",
                    "type":"address"
                }
            ],
            "name":"getRelayTxNonce",
            "outputs":[
                {
                    "internalType":"uint64",
                    "name":"",
                    "type":"uint64"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                }
            ],
            "name":"getRoleAdmin",
            "outputs":[
                {
                    "internalType":"bytes32",
                    "name":"",
                    "type":"bytes32"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"getVersion",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "stateMutability":"pure",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                },
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"grantRole",
            "outputs":[

            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                },
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"hasRole",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"bytes[]",
                    "name":"_data",
                    "type":"bytes[]"
                },
                {
                    "components":[
                        {
                            "internalType":"address",
                            "name":"token",
                            "type":"address"
                        },
                        {
                            "internalType":"bytes",
                            "name":"permit",
                            "type":"bytes"
                        }
                    ],
                    "internalType":"struct JetonForwarder.PayForGasAsset",
                    "name":"_payForGas",
                    "type":"tuple"
                },
                {
                    "internalType":"address",
                    "name":"_signer",
                    "type":"address"
                },
                {
                    "internalType":"bytes",
                    "name":"_sig",
                    "type":"bytes"
                },
                {
                    "internalType":"uint8",
                    "name":"takeTokenPercent",
                    "type":"uint8"
                }
            ],
            "name":"relayCall",
            "outputs":[

            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                },
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"renounceRole",
            "outputs":[

            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"bytes32",
                    "name":"role",
                    "type":"bytes32"
                },
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"revokeRole",
            "outputs":[

            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"contract IJetonRouter",
                    "name":"_jetonRouter",
                    "type":"address"
                }
            ],
            "name":"setJetonRouter",
            "outputs":[

            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"bytes4",
                    "name":"interfaceId",
                    "type":"bytes4"
                }
            ],
            "name":"supportsInterface",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "stateMutability":"payable",
            "type":"receive"
        }
    ]
}
